//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLLDGV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichDay
    {
        public System.Guid MaLich { get; set; }
        public string TenMH { get; set; }
        public System.Guid NhomHP { get; set; }
        public string PhongHoc { get; set; }
        public Nullable<System.Guid> GVDay { get; set; }
        public string ThuNgay { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string GioBatDau { get; set; }
        public string GioKetThuc { get; set; }
    
        public virtual GIAOVIEN GIAOVIEN { get; set; }
        public virtual HocPhan HocPhan { get; set; }
        public virtual TietHoc TietHoc { get; set; }
        public virtual TietHoc TietHoc1 { get; set; }
        public virtual PHONG PHONG { get; set; }
        public virtual MonHoc MonHoc { get; set; }
        public virtual THU THU { get; set; }
    }
}
