//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLLDGV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public System.Guid MaMail { get; set; }
        public System.Guid NguoiGui { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayGui { get; set; }
        public string Tinhtrang { get; set; }
    
        public virtual GIAOVIEN GIAOVIEN { get; set; }
    }
}
